<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<link name="base_link">
    <visual>
        <geometry>
            <cylinder radius="${base_raduis}" length="${base_height}"/>
        </geometry>
        <material name="Cyan">
            <color rgba="0 1.0 1.0 1.0"/>
        </material>
    </visual>
</link>

<xacro:macro name="wheel" params="prefix y_reflect">
  <link name="${prefix}_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="Gray">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
  </link>

  <joint name="${prefix}_joint" type="continuous">
    <parent link="base_link"/>
    <child link="${prefix}_link"/>
    <origin xyz="${wheel_xoff} ${y_reflect*(wheelbase/2)} ${wheel_radius - base_height/2 + floor_gap}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>
</xacro:macro>

<xacro:wheel prefix="drive_wheel_l" y_reflect="1" />
<xacro:wheel prefix="drive_wheel_r" y_reflect="-1" />

</robot>